development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stots_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stots_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stots_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
