#!/usr/bin/env ruby

scripts = %w(pivotal_tracker airbrake_errors airbrake_projects)

threads = scripts.map do |script|
  Thread.new do
    loop do
      puts "Running script #{script}"
      `touch log/#{script}.log`
      success = `ruby script/#{script}.rb >> log/#{script}.log`
      if success
        puts "Script #{script} went OK."
        sleep 1
      else
        puts "Script #{script} FAILED! Will retry in 100 seconds."
        sleep 100
      end
    end
  end
end

threads.each(&:join)
